"""Add the help card to the vb::kimodo_motion HDA and save it (unpacked) to houdini/otls/."""
import hou, os

_HERE = os.path.dirname(__file__)

HELP_CARD = (
    "= Kimodo Motion Generator =\n"
    "\n"
    "#type: node\n"
    "#context: sop\n"
    "#tags: kimodo, motion, ai, kinefx, animation\n"
    "\n"
    "Generates 3D human motion from a text prompt using NVIDIA Kimodo, outputting a\n"
    "77-joint SOMA skeleton (animated + rest poses) plus a skinned body mesh, all\n"
    "compatible with Houdini KineFX.\n"
    "\n"
    "== Overview ==\n"
    "\n"
    "The node connects to a running [Kimodo|https://github.com/nv-tlabs/kimodo]\n"
    "inference server (resident mode: the model is preloaded once). Press __Generate__\n"
    "to submit a prompt; the finished NPZ is downloaded over HTTP into __Download Dir__\n"
    "and the skeleton is rebuilt each frame. The server can run on this machine or a\n"
    "remote GPU box \u2014 set __API Server URL__ accordingly.\n"
    "\n"
    "== Quick Start ==\n"
    "\n"
    "# Start the Docker services (`docker compose -f docker-compose.bridge.yaml up text-encoder -d`, then `up api -d`).\n"
    "# Set __Prompt__ and __Duration__, then press __Generate__. Watch __Status__; the\n"
    "  node cooks automatically when the NPZ has downloaded.\n"
    "# The clip starts on __Start Frame__ and keeps its real duration at your scene FPS\n"
    "  (__Retime to Scene FPS__, on by default). __Clip__ shows its length.\n"
    "# To get a deforming body: drop a __KineFX Joint Deform__ (`kinefx::jointdeform`)\n"
    "  and wire the three outputs straight across: 0 -> 0 (__Rest Geometry__),\n"
    "  1 -> 1 (__Capture Pose__), 2 -> 2 (__Animated Pose__) \u2014 the same order as\n"
    "  Houdini's Test Geometry characters.\n"
    "\n"
    "== Writing Prompts ==\n"
    "\n"
    "Phrasing changes the result more than any parameter on this node. The figures below\n"
    "are measured from generated clips: _airborne_ is the highest moment both toes leave\n"
    "the ground, _hip_ is pelvis height against a standing height of about 0.98.\n"
    "\n"
    "__Name the body mechanics, not the intent.__ At the same duration,\n"
    "`a person jumps forward and lands on both feet` reaches 0.22 airborne, while\n"
    "`a person leaps high into the air with both feet off the ground` reaches 0.94.\n"
    "Likewise `crouches low to the ground` only reaches hip 0.72, where\n"
    "`squats down deeply, knees bent, hips near the floor` reaches 0.24.\n"
    "\n"
    "__A beat is weaker inside a timeline than on its own.__ A segment spends its opening\n"
    "transitioning out of the previous motion, leaving less time for its own action.\n"
    "`a person stands up and turns around` turns 173 degrees generated alone, but only 18\n"
    "degrees as segment 6 of 8. Generate a beat by itself to check it works, then add it\n"
    "to the timeline. This is not caused by what precedes it: after a neutral standing\n"
    "segment the same turn still managed only 73 degrees.\n"
    "\n"
    "__Split a weak segment rather than lengthening it.__ That turn managed 64 degrees as\n"
    "one 2.25 s segment and 154 degrees at 3.50 s, but 193 degrees when split into\n"
    "`stands up from a squat` plus `turns around to face the opposite direction` for the\n"
    "same total time. Ballistic actions behave the opposite way: doubling the jump from\n"
    "2.0 s to 4.0 s made it worse, because the model spreads the action over whatever\n"
    "duration it is given.\n"
    "\n"
    "__Do not prompt for finger or hand detail.__ Kimodo predicts on the 30-joint\n"
    "somaskel30, which strips hand detail, then converts to 77 joints on output. The\n"
    "fingers you get back are reconstructed, never generated. Set __Blend Fingers__ to 0\n"
    "on Biped Retarget for the same reason.\n"
    "\n"
    "== Parameters ==\n"
    "\n"
    "API Server URL:\n"
    "    URL of the running `kimodo_server`. Default: `http://localhost:8001`.\n"
    "    Point this at the GPU host if the server runs elsewhere.\n"
    "\n"
    "Download Dir:\n"
    "    Local folder where finished NPZ files are downloaded from the server over\n"
    "    HTTP. Default: `$HIP/kimodo_cache`.\n"
    "\n"
    "Prompt:\n"
    "    Natural language description of the desired motion.\n"
    '    Examples: "a person walks forward", "someone waves their hand".\n'
    "\n"
    "Duration (s):\n"
    "    Length of the generated motion in seconds. At 30 fps, 3 s = 90 frames.\n"
    "\n"
    "Model:\n"
    "    Kimodo model variant. Default: Kimodo-SOMA-RP-v1.1.\n"
    "\n"
    "Force Regenerate:\n"
    "    Bypass the server cache and re-run inference even if a matching clip exists.\n"
    "\n"
    "Constraints File / Constraints JSON:\n"
    "    Optional [Kimodo constraints|https://research.nvidia.com/labs/sil/projects/kimodo/docs/key_concepts/constraints.html]\n"
    "    that steer the generated motion to hit spatial targets \u2014 a root 2D path or\n"
    "    waypoints, full-body keyframes, or end-effector (hand/foot) targets. Provide a\n"
    "    list of constraint dicts: either point __Constraints File__ at a `*.json`\n"
    "    (e.g. one exported from the Kimodo demo), or paste it into __Constraints JSON__\n"
    "    (which takes precedence). Targets are in Kimodo's space: Y-up, metres, +Z\n"
    "    forward, with the root at XZ = (0, 0) on frame 0 \u2014 the same world space this\n"
    "    node outputs. Simplest type, a `root2d` waypoint set:\n"
    "    {{{\n"
    '    [{"type": "root2d", "frame_indices": [0, 90], "smooth_root_2d": [[0,0],[2,1]]}]\n'
    "    }}}\n"
    "    Leave both empty for unconstrained generation.\n"
    "\n"
    ":input 0 \u2014 Root Path / Waypoints (optional):\n"
    "    Connect geometry to build a `root2d` constraint without writing JSON. Each\n"
    "    point's world XZ becomes a `smooth_root_2d` target (Houdini XZ maps 1:1 to\n"
    "    Kimodo's space). Points carrying an integer `frame` point attribute become\n"
    "    sparse waypoints at those frames (you control the timing); otherwise the points\n"
    "    (in order \u2014 e.g. a resampled polyline) are spread evenly across the clip as a\n"
    "    denser path. The result is appended to any JSON constraints above.\n"
    "\n"
    "Create Pose Rig / Pose Constraint / Pose Keyframes (input 1):\n"
    "    Author full-body or end-effector constraints by posing a skeleton instead of\n"
    "    writing JSON. Press __Create Pose Rig__: it drops an independent A-pose rig (+ a\n"
    "    KineFX Rig Pose) into the network and wires it to __input 1__ \u2014 no wiring from\n"
    "    this node's own outputs. Pose / keyframe that rig, then list the frames to sample\n"
    "    in __Pose Keyframes__ (e.g. `0 45 89`); the posed joints at each are converted to\n"
    "    a Kimodo constraint. __Pose Constraint__ chooses Full-Body (whole skeleton) or\n"
    "    End-Effector \u2014 for the latter, toggle which of Left/Right Hand/Foot to pin (the\n"
    "    rest of the body stays free). The rig must be one this button created (it carries\n"
    "    the rotation convention the conversion inverts). Empty __Pose Keyframes__ = off.\n"
    "\n"
    "Generate:\n"
    "    Submits the prompt to `<API Server URL>/generate` and returns immediately with\n"
    "    a job ID. A background thread polls for progress, so Houdini stays responsive.\n"
    "    When done, the NPZ is downloaded to __Download Dir__, __NPZ Path__ is set to it,\n"
    "    and the node recooks.\n"
    "\n"
    "Cancel:\n"
    "    Cancels the job. The resident server can't interrupt an already-running\n"
    "    generation \u2014 Cancel stops a queued job or discards the result.\n"
    "\n"
    "Status:\n"
    "    Read-only. Shows the live job state: Queued, Running... (Ns), Downloading...,\n"
    "    Done (Ns), Failed, or Cancelled. __Test Connection__ (Server tab) also reports here.\n"
    "\n"
    "Clip:\n"
    "    Read-only. Length of the last generated clip in samples and seconds.\n"
    "\n"
    "Start Frame / Retime to Scene FPS / Source FPS (Output tab):\n"
    "    The clip begins on __Start Frame__; the first sample holds before it and the\n"
    "    last after it. Kimodo generates at 30 fps (__Source FPS__). With __Retime__ on,\n"
    "    scene frames are mapped onto clip samples so a 3 s clip lasts 3 s whether the\n"
    "    scene runs at 24, 25 or 30 fps (nearest sample, no blending). Off = one clip\n"
    "    sample per scene frame, i.e. the clip plays slower at 24 fps.\n"
    "\n"
    "NPZ Path:\n"
    "    The `.npz` the node reads to build the skeleton (a file field, *.npz). Set by\n"
    "    Generate, or point it at any compatible NPZ by hand to load a clip produced\n"
    "    outside this node \u2014 no Generate or server needed.\n"
    "\n"
    "== Output Geometry ==\n"
    "\n"
    "Four outputs, all in the same world space. World rotations use Houdini's\n"
    "row-vector convention (transposed from Kimodo's matrices).\n"
    "\n"
    ":output 0 \u2014 Rest Geometry:\n"
    "    The SOMA77 body mesh in its bind pose, with a KineFX `boneCapture` attribute\n"
    "    (weights + bind from Kimodo's skinning). Drive it with `kinefx::jointdeform`.\n"
    "\n"
    ":output 1 \u2014 Capture Pose:\n"
    "    The A-pose rest skeleton the mesh is bound to (feet on floor). `name` +\n"
    "    `transform`. Use as the rest skeleton for the deformer.\n"
    "\n"
    ":output 2 \u2014 Animated Pose:\n"
    "    Per-frame animated skeleton. Carries `name`, `path`, `parent_id`, `transform`\n"
    "    (float[9] world rotation) and `localtransform` (float[16] local 4x4).\n"
    "\n"
    "    When the NPZ carries Kimodo's foot-contact labels, an `int` attribute\n"
    "    `contact` is added: 1 on a foot joint while it is planted that frame, 0\n"
    "    everywhere else. Contacts are detected on the ankle and toe base of each\n"
    "    side. In a 6-channel SOMA77 NPZ the two ToeEnd joints repeat their ToeBase\n"
    "    value, so treat them as redundant; in a 4-channel NPZ they are not covered\n"
    "    at all and stay 0. NPZs without the labels get no `contact` attribute.\n"
    "\n"
    ":output 3 \u2014 T-Pose:\n"
    "    A T-pose skeleton (`name` + `transform`) for reference / retargeting. Feed it\n"
    "    to a Rig Stash Pose (input 1, match by name) to give Biped Setup a real rest pose.\n"
    "\n"
    "Deform graph: `kinefx::jointdeform` with outputs 0, 1, 2 wired to inputs 0, 1, 2 \u2014\n"
    "the body follows the animation and returns to bind at rest.\n"
    "\n"
    "== SOMA77 Skeleton Hierarchy ==\n"
    "\n"
    "{{{\n"
    "Hips (0)\n"
    "  Spine1-Spine2-Chest\n"
    "    Neck1-Neck2-Head-HeadEnd/Jaw/LeftEye/RightEye\n"
    "    LeftShoulder-LeftArm-LeftForeArm-LeftHand  [+ fingers 15-38]\n"
    "    RightShoulder-RightArm-RightForeArm-RightHand  [+ fingers 43-66]\n"
    "  LeftLeg-LeftShin-LeftFoot-LeftToeBase-LeftToeEnd  [67-71]\n"
    "  RightLeg-RightShin-RightFoot-RightToeBase-RightToeEnd  [72-76]\n"
    "}}}\n"
    "\n"
    "== Notes ==\n"
    "\n"
    "* The server preloads the model and loads weights from the local HuggingFace\n"
    "  cache offline; the weights must be cached first (a prior generation, or\n"
    "  `huggingface-cli download nvidia/Kimodo-SOMA-RP-v1.1`).\n"
    "* The model stays resident in VRAM while the server runs \u2014 stop the api container\n"
    "  to free it.\n"
    "* __mock mode__ (MOCK_MODE=1) returns `dev_reference.npz` without inference, for\n"
    "  HDA development without a GPU.\n"
    "* Port 8000 is reserved by Docker Desktop on Windows; the API defaults to __8001__.\n"
    "* Results are cached by prompt + duration + model; enable __Force Regenerate__ to\n"
    "  bypass the cache.\n"
    "\n"
    "@related\n"
    "- [Joint Deform|Node:sop/kinefx::jointdeform]\n"
    "- [Rig Pose|Node:sop/kinefx::rigpose]\n"
)


def main():
    lib  = "vb_kimodo_motion_1.1.hda"   # keep in sync with create_hda._LIBRARY
    src  = os.path.join(_HERE, "..", lib)
    dest = os.path.join(_HERE, "..", "houdini", "otls", lib)
    hou.hda.installFile(src)
    defs = hou.hda.definitionsInFile(src)
    assert len(defs) == 1, "expected exactly one definition in %s, got %s" % (src, [d.nodeTypeName() for d in defs])
    hda_def = defs[0]
    hda_def.addSection("Help", HELP_CARD)
    # Empty the expanded directory but keep it: Houdini saves expanded only into an
    # existing directory, and a stale sibling definition must not survive a rename.
    import shutil
    if os.path.isdir(dest):
        for entry in os.listdir(dest):
            p = os.path.join(dest, entry)
            shutil.rmtree(p) if os.path.isdir(p) else os.remove(p)
    else:
        os.makedirs(dest)
    hda_def.save(dest)
    print(f"Saved: {dest}  type: {hda_def.nodeTypeName()}  (help {len(hda_def.embeddedHelp())} chars)")


if __name__ == "__main__":
    main()
