"""Add the help card to the kimodo_motion HDA and save it (unpacked) to hda/."""
import hou, os

_HERE = os.path.dirname(__file__)

HELP_CARD = (
    "= Kimodo Motion Generator =\n"
    "\n"
    "#type: node\n"
    "#context: sop\n"
    "#tags: kimodo, motion, ai, kinefx, animation\n"
    "\n"
    "Generates 3D human motion from a text prompt using NVIDIA Kimodo, outputting a\n"
    "77-joint SOMA skeleton (animated + rest poses) plus a skinned body mesh, all\n"
    "compatible with Houdini KineFX.\n"
    "\n"
    "== Overview ==\n"
    "\n"
    "The node connects to a running [Kimodo|https://github.com/nv-tlabs/kimodo]\n"
    "inference server (resident mode: the model is preloaded once). Press __Generate__\n"
    "to submit a prompt; the finished NPZ is downloaded over HTTP into __Download Dir__\n"
    "and the skeleton is rebuilt each frame. The server can run on this machine or a\n"
    "remote GPU box — set __API Server URL__ accordingly.\n"
    "\n"
    "== Quick Start ==\n"
    "\n"
    "# Start the Docker services (`docker compose -f docker-compose.bridge.yaml up text-encoder -d`, then `up api -d`).\n"
    "# Set __Prompt__ and __Duration__, then press __Generate__. Watch __Status__; the\n"
    "  node cooks automatically when the NPZ has downloaded.\n"
    "# Set the Houdini frame range to match the clip and play back.\n"
    "# To get a deforming body: drop a __Labs/KineFX Joint Deform__ (`kinefx::jointdeform`)\n"
    "  and wire input 0 = __Rest Geometry__ (output 2), input 1 = __Capture Pose__\n"
    "  (output 1), input 2 = __Animated Pose__ (output 0).\n"
    "\n"
    "== Parameters ==\n"
    "\n"
    "API Server URL:\n"
    "    URL of the running `kimodo_server`. Default: `http://localhost:8001`.\n"
    "    Point this at the GPU host if the server runs elsewhere.\n"
    "\n"
    "Download Dir:\n"
    "    Local folder where finished NPZ files are downloaded from the server over\n"
    "    HTTP. Default: `$HIP/kimodo_cache`.\n"
    "\n"
    "Prompt:\n"
    "    Natural language description of the desired motion.\n"
    '    Examples: "a person walks forward", "someone waves their hand".\n'
    "\n"
    "Duration (s):\n"
    "    Length of the generated motion in seconds. At 30 fps, 3 s = 90 frames.\n"
    "\n"
    "Model:\n"
    "    Kimodo model variant. Default: Kimodo-SOMA-RP-v1.1.\n"
    "\n"
    "Force Regenerate:\n"
    "    Bypass the server cache and re-run inference even if a matching clip exists.\n"
    "\n"
    "Constraints File / Constraints JSON:\n"
    "    Optional [Kimodo constraints|https://research.nvidia.com/labs/sil/projects/kimodo/docs/key_concepts/constraints.html]\n"
    "    that steer the generated motion to hit spatial targets — a root 2D path or\n"
    "    waypoints, full-body keyframes, or end-effector (hand/foot) targets. Provide a\n"
    "    list of constraint dicts: either point __Constraints File__ at a `*.json`\n"
    "    (e.g. one exported from the Kimodo demo), or paste it into __Constraints JSON__\n"
    "    (which takes precedence). Targets are in Kimodo's space: Y-up, metres, +Z\n"
    "    forward, with the root at XZ = (0, 0) on frame 0 — the same world space this\n"
    "    node outputs. Simplest type, a `root2d` waypoint set:\n"
    "    {{{\n"
    '    [{"type": "root2d", "frame_indices": [0, 90], "smooth_root_2d": [[0,0],[2,1]]}]\n'
    "    }}}\n"
    "    Leave both empty for unconstrained generation.\n"
    "\n"
    ":input 0 — Root Path / Waypoints (optional):\n"
    "    Connect geometry to build a `root2d` constraint without writing JSON. Each\n"
    "    point's world XZ becomes a `smooth_root_2d` target (Houdini XZ maps 1:1 to\n"
    "    Kimodo's space). Points carrying an integer `frame` point attribute become\n"
    "    sparse waypoints at those frames (you control the timing); otherwise the points\n"
    "    (in order — e.g. a resampled polyline) are spread evenly across the clip as a\n"
    "    denser path. The result is appended to any JSON constraints above.\n"
    "\n"
    "Create Pose Rig / Pose Constraint / Pose Keyframes (input 1):\n"
    "    Author full-body or end-effector constraints by posing a skeleton instead of\n"
    "    writing JSON. Press __Create Pose Rig__: it drops an independent A-pose rig (+ a\n"
    "    KineFX Rig Pose) into the network and wires it to __input 1__ — no wiring from\n"
    "    this node's own outputs. Pose / keyframe that rig, then list the frames to sample\n"
    "    in __Pose Keyframes__ (e.g. `0 45 89`); the posed joints at each are converted to\n"
    "    a Kimodo constraint. __Pose Constraint__ chooses Full-Body (whole skeleton) or\n"
    "    End-Effector — for the latter, toggle which of Left/Right Hand/Foot to pin (the\n"
    "    rest of the body stays free). The rig must be one this button created (it carries\n"
    "    the rotation convention the conversion inverts). Empty __Pose Keyframes__ = off.\n"
    "\n"
    "Generate:\n"
    "    Submits the prompt to `<API Server URL>/generate` and returns immediately with\n"
    "    a job ID. A background thread polls for progress, so Houdini stays responsive.\n"
    "    When done, the NPZ is downloaded to __Download Dir__, __NPZ Path__ is set to it,\n"
    "    and the node recooks.\n"
    "\n"
    "Cancel:\n"
    "    Cancels the job. The resident server can't interrupt an already-running\n"
    "    generation — Cancel stops a queued job or discards the result.\n"
    "\n"
    "Status:\n"
    "    Read-only. Shows the live job state: Queued, Running... (Ns), Downloading...,\n"
    "    Done (Ns), Failed, or Cancelled.\n"
    "\n"
    "NPZ Path:\n"
    "    The `.npz` the node reads to build the skeleton (a file field, *.npz). Set by\n"
    "    Generate, or point it at any compatible NPZ by hand to load a clip produced\n"
    "    outside this node — no Generate or server needed.\n"
    "\n"
    "== Output Geometry ==\n"
    "\n"
    "Four outputs, all in the same world space. World rotations use Houdini's\n"
    "row-vector convention (transposed from Kimodo's matrices).\n"
    "\n"
    ":output 0 — Animated Pose:\n"
    "    Per-frame animated skeleton. Carries `name`, `path`, `parent_id`, `transform`\n"
    "    (float[9] world rotation) and `localtransform` (float[16] local 4x4).\n"
    "\n"
    "    When the NPZ carries Kimodo's foot-contact labels, an `int` attribute\n"
    "    `contact` is added: 1 on a foot joint while it is planted that frame, 0\n"
    "    everywhere else. Contacts are detected on the ankle and toe base of each\n"
    "    side. In a 6-channel SOMA77 NPZ the two ToeEnd joints repeat their ToeBase\n"
    "    value, so treat them as redundant; in a 4-channel NPZ they are not covered\n"
    "    at all and stay 0. NPZs without the labels get no `contact` attribute.\n"
    "\n"
    ":output 1 — Capture Pose:\n"
    "    The A-pose rest skeleton the mesh is bound to (feet on floor). `name` +\n"
    "    `transform`. Use as the rest skeleton for the deformer.\n"
    "\n"
    ":output 2 — Rest Geometry:\n"
    "    The SOMA77 body mesh in its bind pose, with a KineFX `boneCapture` attribute\n"
    "    (weights + bind from Kimodo's skinning). Drive it with `kinefx::jointdeform`.\n"
    "\n"
    ":output 3 — T-Pose:\n"
    "    A T-pose skeleton (`name` + `transform`) for reference / retargeting.\n"
    "\n"
    "Deform graph: `kinefx::jointdeform` with input 0 = output 2, input 1 = output 1,\n"
    "input 2 = output 0 — the body follows the animation and returns to bind at rest.\n"
    "\n"
    "== SOMA77 Skeleton Hierarchy ==\n"
    "\n"
    "{{{\n"
    "Hips (0)\n"
    "  Spine1-Spine2-Chest\n"
    "    Neck1-Neck2-Head-HeadEnd/Jaw/LeftEye/RightEye\n"
    "    LeftShoulder-LeftArm-LeftForeArm-LeftHand  [+ fingers 15-38]\n"
    "    RightShoulder-RightArm-RightForeArm-RightHand  [+ fingers 43-66]\n"
    "  LeftLeg-LeftShin-LeftFoot-LeftToeBase-LeftToeEnd  [67-71]\n"
    "  RightLeg-RightShin-RightFoot-RightToeBase-RightToeEnd  [72-76]\n"
    "}}}\n"
    "\n"
    "== Notes ==\n"
    "\n"
    "* The server preloads the model and loads weights from the local HuggingFace\n"
    "  cache offline; the weights must be cached first (a prior generation, or\n"
    "  `huggingface-cli download nvidia/Kimodo-SOMA-RP-v1.1`).\n"
    "* The model stays resident in VRAM while the server runs — stop the api container\n"
    "  to free it.\n"
    "* __mock mode__ (MOCK_MODE=1) returns `dev_reference.npz` without inference, for\n"
    "  HDA development without a GPU.\n"
    "* Port 8000 is reserved by Docker Desktop on Windows; the API defaults to __8001__.\n"
    "* Results are cached by prompt + duration + model; enable __Force Regenerate__ to\n"
    "  bypass the cache.\n"
    "\n"
    "@related\n"
    "- [Joint Deform|Node:sop/kinefx::jointdeform]\n"
    "- [Rig Pose|Node:sop/kinefx::rigpose]\n"
)


def main():
    src  = os.path.join(_HERE, "..", "kimodo_motion.hda")
    dest = os.path.join(_HERE, "..", "hda", "kimodo_motion.hda")
    hou.hda.installFile(src)
    hda_def = hou.hda.definitionsInFile(src)[0]
    hda_def.addSection("Help", HELP_CARD)
    hda_def.save(dest)
    print(f"Saved: {dest}  (help {len(hda_def.embeddedHelp())} chars)")


if __name__ == "__main__":
    main()
